
[metadata]
name = hesma

[options]
packages = find:
include_package_data = True

[options.package_data]
hesma =
    static/css/*.css
    static/images/*.jpg
    static/images/*.png

[options.extras_require]
tests =
    pytest-invenio>=2.1.0,<3.0.0

[options.entry_points]
invenio_base.blueprints =
    hesma_views = hesma.views:create_blueprint
invenio_assets.webpack =
    hesma_theme = hesma.webpack:theme
